server:
  address: localhost
  port: 8080
  ssl:
    enabled: false
springdoc:
  show-actuator: false
  swagger-ui:
    groups-order: desc
    disable-swagger-default-url: true
spring:
  application:
    name: modulo-spring
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/spring
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migrations
management:
  metrics:
    tags:
      app-name: ${spring.application.name}
  datadog:
    metrics:
      export:
        api-key: ${DATADOG_API_KEY}
        application-key: ${DATADOG_APP_KEY}
        uri: ${DATADOG_URI}
        step: 10s
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
        fields: [x-correlationID]
      remote-fields: [x-correlationID]
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      my_custom_tag: ${spring.application.name}
